LIMITE_EMPRESTIMOS_COMUM = 3
LIMITE_EMPRESTIMOS_PREMIUM = 5
LIMITE_EMPRESTIMOS_FUNCIONARIO = 10
LIMITE_EMPRESTIMOS_PROFESSOR = 15
LIMITE_EMPRESTIMOS_PADRAO = 1

PRAZO_DIAS_COMUM = 7
PRAZO_DIAS_PREMIUM = 14
PRAZO_DIAS_FUNCIONARIO = 30
PRAZO_DIAS_PROFESSOR = 60
PRAZO_DIAS_PADRAO = 3

MULTA_POR_DIA_COMUM = 2
MULTA_POR_DIA_PREMIUM = 1
MULTA_POR_DIA_FUNCIONARIO = 0
MULTA_POR_DIA_PROFESSOR = 0
MULTA_POR_DIA_PADRAO = 3
